# name: Deploy to Firebase

# on:
#   push:
#     branches:
#       - main # Triggers deployment when pushing to main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18 # Ensure compatibility with Next.js

#       - name: Install Dependencies
#         run: yarn install --frozen-lockfile # Ensures dependencies match yarn.lock

#       - name: Create .env file
#         run: |
#           touch .env.local  # Next.js uses .env.local for environment variables
#           echo "OPENAI_API_KEY=${{ secrets.OPENAI_KEY }}" >> .env.local

#       - name: Build Website
#         run: yarn build # Next.js build step

#       - name: Deploy to Firebase
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
#           channelId: live
#           projectId: personalsite-989c9
